[build]
publish = "."

[[redirects]]
from = "/offerte/atalanta"
to = "/Offerte/Atalanta/"
status = 301
force = true

[[redirects]]
from = "/offerte/atalanta/*"
to = "/Offerte/Atalanta/:splat"
status = 200
force = true
